sudo: false
language: node_js
node_js:
- '10'
env:
  global:
    - IDE_VERSION=1.8.5
    - SENSEBOXCORE_VERSION=1.2.1
    - ARDUINO_SAMD_VERSION=1.6.18
    - SENSEBOXCORE_URL=https://raw.githubusercontent.com/sensebox/senseBoxMCU-core/master/package_sensebox_index.json
before_script:
  - echo $TRAVIS_BUILD_DIR
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - arduino --install-boards arduino:samd:$ARDUINO_SAMD_VERSION
  # A little hack to install the local and not released senseBox-MCU core
  # 1. Install the latest published core version
  # 2. Remove the installed files
  # 3. Create the version folder again
  # 4. Copy the local unpublished core package
  - arduino --pref boardsmanager.additional.urls=$SENSEBOXCORE_URL --install-boards sensebox:samd:$SENSEBOXCORE_VERSION
  - rm -rf /home/travis/.arduino15/packages/sensebox/hardware/samd/1.2.1
  - mkdir -p /home/travis/.arduino15/packages/sensebox/hardware/samd/1.2.1
  - cp -a $TRAVIS_BUILD_DIR/arduino/samd/. /home/travis/.arduino15/packages/sensebox/hardware/samd/1.2.1
script:
  - npm run test
  - arduino --verbose-build --verify --board sensebox:samd:sb:power=on /home/travis/.arduino15/packages/sensebox/hardware/samd/1.2.1/libraries/tests/examples/mcu_component_test/mcu_component_test.ino
